name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    container: archlinux/base
    steps:
      - run: pacman -Syu --noconfirm base base-devel shellcheck
      - uses: actions/checkout@v2

      - name: Option parsing consistency
        run: tests/parseopt-consistency

      - name: Shellcheck
        if: success() || failure() # Do not fail-fast
        run: make shellcheck
